name: 首頁登入

vars:
  base_url: "https://isocialwork-dev.nchc.org.tw"

vars_from:
  file: sessions.csv
  mode: sequential

stages:
  - duration: 10s
    target: 10
  - duration: 10s
    target: 10
  - duration: 10s
    target: 0

steps:
  - name: GET /dashboard
    method: GET
    url: "{{vars.base_url}}/dashboard"
    headers:
      Cookie: "{{data.session_cookie}}"
    assertions:
      status: 200
